### ISSUE TITLE
demo data folder incomplete ?

### ISSUE THREAD

**Issue by dmaugis** [erleben/OpenTissue#1]
I had many issues compiling OpenTissue on Ubuntu 16, but succeeded after a few modifications in the 
c++ code and CMakeLists.txt
I cannot test compilation under Windows as I suffer from a Micro$oft allergy atm...
I think there should be very little work needed to make a version compilable on both platforms.
My version is there: https://github.com/dmaugis/OpenTissue, if someone want's to merge.

However, lots of the exemples I cannot test, because the data folder is missing some files (the obj folder, knee files etc...) is there a place I could get them ?

Thanks

**Comment by erleben** [comment]
There was a *.obj entry in gitignore that made git ingnore all obj files. The *.obj is now removed from gitignore and the missing mesh files are added to the data folder.
