### ISSUE TITLE
Replace DevIL with something less cumbersome

### ISSUE THREAD

**Issue by ricortiz** [erleben/OpenTissue#25]
I think DevIL hard dependency on GLUT is cumbersome and overkill for OT usage of the library (png image output?). You mentioned libImageMagic can accomplish the same, if the purpose is to let the user write to multiple image formats then I agree. But if you are only thinking about supporting png output, then I think using libpng directly is a less cumbersome dependency. 

Thoughts? @erleben

**Comment by erleben** [comment]
Agree it was only intended for frame grabbing. Hardwire to png is fine too. I am not familiar with libpng but a minimum lib solution sounds like a good idea.
