### ISSUE TITLE
Have some questions

### ISSUE THREAD

**Issue by LinLorry** [erleben/OpenTissue#3]
https://github.com/erleben/OpenTissue/blob/ca311cee7ea6f4352a1dc14fdeed0dda57aa7c37/OpenTissue/core/math/math_random.h#L60

When i use this header, i get some errors. I can't find this 'details<T>', but i find 'detail' in there.
https://github.com/erleben/OpenTissue/blob/ca311cee7ea6f4352a1dc14fdeed0dda57aa7c37/OpenTissue/core/math/math_constants.h#L24

Maybe somewhere else have 'details', can you give me some suggests?
Though i use detail::zero<T>() and detail::one<T>() replace original, it also can work.

**Comment by erleben** [comment]
It appears to be a typo. The namespace should be "detail" and not "details"

Thx for reporting this.

**Comment by LinLorry** [comment]
ok, thank you, i can fix by myself
